export const mentalCheckQuestions: string[] = [
  'Bisakah Anda memperkenalkan diri dengan jelas?', // [cite: 17]
  'Apa yang sedang Anda rasakan saat ini?', // [cite: 18]
  'Adakah masalah yang sedang Anda rasakan saat ini? Coba jelaskan.', // [cite: 19]
  'Apakah Anda pernah merasa cemas berlebihan? Kapan dan apa penyebabnya?', // [cite: 20, 21]
  'Pernahkah Anda merasa sangat tidak berguna? Jika ya, mengapa dan bagaimana Anda mengatasinya?', // [cite: 22]
  'Apakah Anda suka memendam masalah sendiri?', // [cite: 23]
  'Bagaimana Anda mengatasi stres?', // [cite: 24]
  'Apa hal yang membuat Anda bahagia?', // [cite: 25]
  'Pernahkah Anda mengalami trauma di masa lalu yang masih membekas?', // [cite: 26]
  'Bagaimana Anda mengatasi rasa trauma tersebut?', // [cite: 28]
  'Apakah Anda pernah merasa ingin mengakhiri hidup? Jika ya, kapan dan kenapa?', // [cite: 29]
  'Apa hal positif yang ada di dalam diri Anda?', // [cite: 30]
  'Apa saja hal negatif yang Anda miliki?', // [cite: 31]
  'Bagaimana cara Anda meminimalisir sifat negatif pada diri Anda?', // [cite: 32]
  'Siapa orang yang biasanya menjadi tempat Anda berkeluh kesah?', // [cite: 33]
  'Apakah Anda nyaman bercerita dengan orang lain? Mengapa?', // [cite: 34]
  'Bagaimana cara Anda mengambil keputusan penting dalam hidup?', // [cite: 35]
  'Apa pengalaman hidup yang paling membentuk diri Anda sekarang?', // [cite: 36]
  'Jika Anda bisa mengubah satu hal tentang diri Anda, apa yang akan Anda ubah dan mengapa?', // [cite: 37]
  'Bagaimana Anda menentukan prioritas dalam hidup?', // [cite: 39]
  'Apa tujuan hidup Anda saat ini?', // [cite: 40]
  'Apa arti kebahagiaan menurut Anda?', // [cite: 41]
  'Bagaimana orang lain menggambarkan diri Anda?', // [cite: 42]
  'Apa pekerjaan impian Anda?', // [cite: 43]
  'Apa yang Anda lakukan saat waktu luang?', // [cite: 44]
  'Siapa panutan Anda dalam hidup?', // [cite: 45]
  'Apa makna kehidupan bagi Anda?', // [cite: 46]
  'Apakah Anda merasa kesepian? Mengapa?', // [cite: 47]
  'Kapan terakhir kali Anda menangis, kenapa, dan bagaimana cara menghentikannya?', // [cite: 48]
  'Apa harapan Anda untuk masa depan?', // [cite: 49]
];
